### ISSUE TITLE
Use nodejs LTS

### ISSUE THREAD

**Issue by banjoh** [andyrbell/mountebank#6]
No particular functional reason besides having the LTS version of node being regularly updated.

```
RUN apk add --update nodejs-lts
```

PS: I do realise it is the same version as you have as well :)

**Comment by andyrbell** [comment]
Hi @banjoh, thanks for the suggestion. 

I was going to make this change when updating to Mountebank 2.2.0. However, after a bit of investigation, it looks like from [Alpline 3.5.0](https://www.alpinelinux.org/posts/Alpine-3.5.0-released.html) onwards nodejs _is_ the LTS version:

> The nodejs package was renamed to nodejs-current and moved to the community repository. The nodejs-lts package was renamed to nodejs. This means that you get the LTS version if you do apk add nodejs.

Although, `apk add nodejs-lts` still works, it must be aliased somehow to `nodejs` because there is no `nodejs-lts` [package listed for Alpline](https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.11) any more. It still installs the same package but it feels safer to stick with `nodejs`.

Thanks again!
